const assert=require('node:assert/strict'),M=require('./study-model.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const at=new Date(2026,8,16,12).getTime();
const tick=(s,now,owner='a',visible=true,action='tick')=>M.advance(s,{now,owner,visible,action});
test('time starts only after an explicit start and persists across serialization',()=>{let s=M.empty();tick(s,at);assert.equal(M.stats(s,at).total,0);tick(s,at,'a',true,'start');tick(s,at+1200);s=M.normalize(JSON.parse(JSON.stringify(s)));assert.equal(M.stats(s,at).total,1200);assert.equal(s.running,true);});
test('pause flushes the last fraction, and resume excludes the pause',()=>{const s=M.empty();tick(s,at,'a',true,'start');tick(s,at+1750,'a',true,'pause');tick(s,at+10000);assert.equal(M.stats(s,at).total,1750);tick(s,at+20000,'a',true,'start');tick(s,at+21000);assert.equal(M.stats(s,at).total,2750);});
test('hidden tabs release ownership and exclude the hidden interval',()=>{const s=M.empty();tick(s,at,'a',true,'start');tick(s,at+750,'a',false);tick(s,at+100000,'a',true);tick(s,at+101000);assert.equal(M.stats(s,at).total,1750);});
test('concurrent tabs cannot double count; a live tab takes over a released lease',()=>{const s=M.empty();tick(s,at,'a',true,'start');tick(s,at+1000,'b');assert.equal(s.owner,'a');tick(s,at+1000,'a');tick(s,at+1500,'a',false);tick(s,at+1500,'b');tick(s,at+2500,'b');tick(s,at+2500,'a');assert.equal(M.stats(s,at).total,2500);assert.equal(s.owner,'b');});
test('closed tabs and a suspended computer do not backfill elapsed wall time',()=>{const s=M.empty();tick(s,at,'a',true,'start');tick(s,at+1000);tick(s,at+3600000,'b');assert.equal(M.stats(s,at).total,1000);tick(s,at+3601000,'b');tick(s,at+7200000,'b');assert.equal(M.stats(s,at).total,2000);});
test('an interrupted reload can acquire an expired lease without adding its gap',()=>{const s=M.empty();tick(s,at,'a',true,'start');tick(s,at+1000);tick(s,at+2000,'new-page');assert.equal(s.owner,'a');tick(s,at+6500,'new-page');assert.equal(s.owner,'new-page');assert.equal(M.stats(s,at).total,1000);});
test('midnight divides the time between local calendar dates',()=>{const start=new Date(2026,8,16,23,59,59,500).getTime(),s=M.empty();tick(s,start,'a',true,'start');tick(s,start+1000);assert.equal(s.days['2026-09-16'],500);assert.equal(s.days['2026-09-17'],500);});
test('clock rollback does not add negative time or freeze future updates',()=>{const s=M.empty();tick(s,at,'a',true,'start');tick(s,at+1000);tick(s,at-10000);tick(s,at-9000);assert.equal(M.stats(s,at).total,2000);});
test('achievement dates persist, and reading undo relocks only relevant achievements',()=>{const course={lessons:[{id:'one'},{id:'two'}],chapters:[{lessons:['one','two']}]},s=M.empty();s.days[M.dayKey(at)]=25*60000;let rows=M.achievements(s,['one','two','invalid'],course,at);M.reconcile(s,rows,at);assert.equal(rows.find(r=>r.id==='time-25').unlocked,true);assert.equal(rows.find(r=>r.id==='chapter-1').unlocked,true);const date=s.earned['time-25'];rows=M.achievements(s,['one'],course,at+1000);M.reconcile(s,rows,at+1000);assert.equal(s.earned['time-25'],date);assert.equal(s.earned['chapter-1'],undefined);assert.equal(rows.find(r=>r.id==='read-all').unlocked,false);});
test('learning days require a minute and do not require consecutive dates',()=>{const s=M.empty();s.days={'2026-09-01':60000,'2026-09-10':60000,'2026-09-16':59000};assert.equal(M.stats(s,at).days,2);s.days['2026-09-16']=60000;assert.equal(M.stats(s,at).days,3);});
test('invalid saved values are discarded and hours can exceed 24',()=>{const s=M.normalize({version:1,days:{bad:10,'2026-09-16':-20,'2026-09-15':NaN},running:'true'});assert.equal(M.stats(s,at).total,0);assert.equal(s.running,false);assert.equal(M.clock(100*3600000+62000),'100:01:02');});
console.log(`${count} study behavior checks passed.`);
