const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require('../../样张/tooling/node_modules/linkedom');const root=path.resolve(__dirname,'..'),site=path.join(root,'site'),math=path.resolve(root,'../课程/site'),course=require('../course.json'),coverage=require('../site/coverage.json');
const docs=new Map();let links=0,formulas=0,exercises=0,diagrams=0;
for(const file of fs.readdirSync(site).filter(f=>f.endsWith('.html'))){const {document:d}=parseHTML(fs.readFileSync(path.join(site,file),'utf8'));docs.set(file,d);const ids=new Set();for(const el of d.querySelectorAll('[id]')){assert(!ids.has(el.id),file+' duplicate '+el.id);ids.add(el.id);}assert(!d.querySelector('.katex-error'));formulas+=d.querySelectorAll('.katex').length;exercises+=d.querySelectorAll('.exercise').length;diagrams+=d.querySelectorAll('[data-steps]').length;assert(!/PLACEHOLDER|EXAMPLES|待补充|TODO/.test(d.body.textContent),file+' placeholder');}
for(const [file,d]of docs)for(const el of d.querySelectorAll('[href],[src]')){const raw=el.getAttribute('href')||el.getAttribute('src');if(!raw||/^(https?:|mailto:|data:)/.test(raw))continue;const u=new URL(raw,'http://local/843/'+file),p=decodeURIComponent(u.pathname);const target=p.startsWith('/843/')?path.join(site,p.slice(5)||'index.html'):path.join(math,p.slice(1)||'index.html');assert(fs.existsSync(target)&&fs.statSync(target).isFile(),'Missing '+file+' '+raw);if(u.hash&&path.extname(target)==='.html'){const doc=target.startsWith(site)?docs.get(path.basename(target)):null;assert((doc||parseHTML(fs.readFileSync(target,'utf8')).document).getElementById(decodeURIComponent(u.hash.slice(1))),'Anchor '+file+' '+raw);}links++;}
for(const [file,doc]of docs)require('../../课程/tooling/check-math-svg.cjs')(doc,file);
for(const name of ['reader.js','reading-parts.js','study-model.js','study.js','diagrams.js','course-data.js'])new vm.Script(fs.readFileSync(path.join(site,name),'utf8'));
const ids=new Set(course.chapters.flatMap(c=>c.lessons.map(l=>l.id))),refs=new Set(course.sources.map(s=>s.id));
for(const c of course.chapters){const d=docs.get(c.id+'.html');for(const l of c.lessons){assert(l.id.startsWith('843-'));assert(l.references.every(r=>refs.has(r)));assert(l.prerequisites.every(id=>ids.has(id)));const el=d.getElementById(l.id);assert.equal(el.querySelectorAll(':scope > .example').length,2);assert.equal(el.querySelectorAll(':scope > .exercise').length,3);for(const ex of el.querySelectorAll(':scope > .exercise'))assert.equal(ex.querySelectorAll('details').length,2);for(const part of el.querySelectorAll('[data-reading-part]')){assert(part.querySelector('[data-part-mark]'));assert(part.querySelector('[data-part-toggle]'));assert(part.querySelector('.part-body').textContent.trim().length>0);}}}
assert.equal(coverage.requirements.length,21);assert.equal(coverage.lessons.length,ids.size);assert(coverage.requirements.every(r=>r.evidence.length&&r.evidence.every(e=>e.examples.length===2&&e.exercises.length===3)));
const mapped=new Set(coverage.requirements.flatMap(r=>r.lessons));assert(coverage.lessons.every(l=>l.scope==='预备基础'||mapped.has(l.id)),'Unmapped required lesson');
const css=fs.readFileSync(path.join(site,'vendor/katex/katex.min.css'),'utf8');for(const m of css.matchAll(/url\(([^)]+)\)/g))assert(fs.existsSync(path.resolve(site,'vendor/katex',m[1].replace(/["']/g,''))));
assert.equal(require('./cases.cjs').length,6);for(const paper of require('./mocks.cjs')){assert.equal(paper.questions.filter(q=>q[0]==='信息技术').reduce((n,q)=>n+q[1],0),100);assert.equal(paper.questions.filter(q=>q[0]==='创新设计').reduce((n,q)=>n+q[1],0),50);}
const result={passed:true,pages:docs.size,lessons:ids.size,officialRequirements:21,localLinksAndAssets:links,formulas,exerciseCards:exercises,interactiveDiagrams:diagrams,cases:6,mockPapers:2,checkedAt:new Date().toISOString()};fs.writeFileSync(path.join(root,'STRUCTURAL-QA.json'),JSON.stringify(result,null,2));console.log(result);
