const fs=require('node:fs'),path=require('node:path'),visual=require('./visuals.cjs'),cases=require('./cases.cjs'),mocks=require('./mocks.cjs');
module.exports=({out,shell,md,exercise,course})=>{
 const lessons=course.chapters.flatMap(c=>c.lessons.map(l=>({...l,url:c.id+'.html#'+l.id}))),link=id=>{const l=lessons.find(l=>l.id===id);if(!l)throw Error(id);return `<a href="${l.url}">${l.title}</a>`;};
 const extras='<section class="block"><h2>把知识连起来，动手完成一份答案</h2><p><a href="cases.html">六个贯穿案例</a> · <a href="mock-a.html">原创模拟卷 A</a> · <a href="mock-b.html">原创模拟卷 B</a> · <a href="templates.html">可打印手绘模板</a> · <a href="code.html">C 与 SQL 代码示范</a></p><p class="muted">两卷各150分：信息技术100分、创新设计50分。细分配分和设计自评标准是教学约定。</p></section>';
 for(const f of ['index.html','contents.html']){const p=path.join(out,f);fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace('</main>',extras+'</main>'));}
 fs.writeFileSync(path.join(out,'cases.html'),shell('贯穿案例册',`<main id="main"><div class="hero"><p class="eyebrow">原创情境 / 从证据到评价</p><h1>六个问题，六条完整的推演</h1><p>所有人物、观察与项目均为教学设定，尚未进行真实调研。阅读时练习判断“哪些是证据、哪些仍是假设”。图示为原创过程示意。</p><nav>${cases.map(c=>`<a href="#case-${c.id}">${c.title.split('：')[0]}</a>`).join(' · ')}</nav></div>${cases.map(c=>`<article class="lesson" id="case-${c.id}"><h2>${c.title}</h2>${Object.entries({evidence:'情境与待验证证据',problem:'问题与约束',options:'比较方案',technology:'技术如何服务问题',walkthrough:'方案推演与图示',evaluation:'怎样知道有用'}).map(([k,title])=>`<section class="block"><h3>${title}</h3>${md(c[k])}</section>`).join('')}${visual(c.visual,'case-'+c.id)}${exercise('case-'+c.id+'-practice','动手改一次方案',...c.practice)}<p>连接课程：${c.links.map(link).join(' · ')}</p></article>`).join('')}</main>`));
 for(const paper of mocks){for(const type of ['信息技术','创新设计']){const sum=paper.questions.filter(q=>q[0]===type).reduce((s,q)=>s+q[1],0);if(sum!==(type==='信息技术'?100:50))throw Error('Incorrect mock total');}fs.writeFileSync(path.join(out,'mock-'+paper.id+'.html'),shell(paper.title,`<main id="main"><div class="hero"><p class="eyebrow">原创模拟 / 150分</p><h1>${paper.title}</h1><p>信息技术100分，创新设计50分。题型和题内配分为训练设计，非官方预测、真题或官方评分细则。先关闭解析独立完成；时间按你的训练节奏自行记录。</p><p><a href="templates.html">打开手绘答题模板</a> · <a href="mock-${paper.id==='a'?'b':'a'}.html">另一套模拟卷</a></p></div>${paper.questions.map(([type,points,prompt,hint,solution],i)=>exercise(`mock-${paper.id}-q${i+1}`,`${i+1}. ${type} · ${points}分`,prompt,hint,solution)).join('')}</main>`));}
 fs.writeFileSync(path.join(out,'templates.html'),shell('手绘练习模板',`<main id="main"><div class="hero print-only-intro"><p class="eyebrow">纸笔实践 / 可打印</p><h1>从第一条线开始</h1><p>使用浏览器打印（Ctrl+P）即可保存PDF或打印。以下模板不带官方答题纸含义；建议先轻画结构，再画细节，最后自评。打印时图形控制和计时面板自动隐藏。</p></div><section class="print-grid">${['01 直线：标两端，一笔连接；画10条不同方向线','02 椭圆：先轴线，后轮廓；画6个不同宽高椭圆','03 方体：外框—结构—投口—检修—标注','04 一点透视：视平线、消失点、正面、深度线','05 人物场景：动作线、视线、触达、使用路径','06 界面线框：目标信息、主操作、返回和异常','07 四格故事：情境 → 行动 → 反馈 → 结果','08 一页方案：问题 / 主图 / 细节 / 实现与评价'].map((s,i)=>`<div class="print-cell"><h2>${s}</h2>${i===6?'<svg viewBox="0 0 500 160" aria-label="四格故事空白框">'+[0,1,2,3].map(j=>`<rect x="${j*125+2}" y="8" width="115" height="140" fill="none" stroke="#8996a2"/>`).join('')+'</svg>':'<p class="muted">练习日期：________　任务：________________</p>'}</div>`).join('')}</section><section class="block"><h2>完成后自评</h2><p>结构和比例是否一致？人物是否真的在使用？箭头与文字是否对应？是否有失败后的路径？标注能否读清？每项0—2分仅用于定位下次练习重点，不是官方评分。</p><p>${link('843-lines-forms')} · ${link('843-perspective')} · ${link('843-answer-layout')}</p></section></main>`));
 const codeDir=path.join(__dirname,'../examples');fs.mkdirSync(path.join(out,'examples'),{recursive:true});
 const programs=fs.readdirSync(codeDir).filter(f=>/\.(c|sql)$/.test(f));
 let body='<main id="main"><div class="hero"><p class="eyebrow">本地示范 / 先理解，再读代码</p><h1>把步骤翻译成 C 与 SQL</h1><p>正文先用伪代码说明过程。这里的完整C程序与固定数据SQL可下载，编译与执行核验记录见源码QA。无需在线运行服务或先安装开发环境即可阅读。</p></div>';
 for(const name of programs){const code=fs.readFileSync(path.join(codeDir,name),'utf8');fs.copyFileSync(path.join(codeDir,name),path.join(out,'examples',name));body+=`<section class="block"><h2>${name}</h2><p><a href="examples/${name}" download>下载源码</a></p>${md('```'+(name.endsWith('.c')?'C':'SQL')+'\n'+code+'\n```')}</section>`;}
 body+='<p>C语言提示：#include引入声明；int是整数；size_t是长度/下标类型；*表示指针；&amp;取得地址；-&gt;访问指针所指结构体字段；NULL表示空指针；assert检查预期条件。函数输入边界在注释中声明，测试空输入、重复值、失败与正常路径。</p></main>';fs.writeFileSync(path.join(out,'code.html'),shell('代码示范',body));
 for(const file of ['cases.html','mock-a.html','mock-b.html','code.html']){const p=path.join(out,file);fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace('<main id="main">','<main id="main" class="reading-sheet">'));}
};
